/**
 * YETO Indicator Catalog - Section 7 Implementation
 * 
 * Complete indicator catalog covering 2010→Present with all 10 indicator families:
 * 1) Macro & Real Economy
 * 2) Prices & Cost of Living (governorate-level where possible)
 * 3) Monetary & Financial System (split system)
 * 4) Public Finance & Governance
 * 5) Trade & External Sector (including ports/fuel)
 * 6) Humanitarian & Social Outcomes
 * 7) Aid, Projects, Accountability
 * 8) Conflict & Political Economy Linkages
 * 9) Private Sector & Firms (documented only)
 * 10) Sanctions/Restrictions Context (informational only)
 */

// ============================================================================
// INDICATOR FAMILY DEFINITIONS
// ============================================================================

export type IndicatorFamily = 
  | 'macro_real_economy'
  | 'prices_cost_of_living'
  | 'monetary_financial'
  | 'public_finance'
  | 'trade_external'
  | 'humanitarian_social'
  | 'aid_projects'
  | 'conflict_political'
  | 'private_sector'
  | 'sanctions_restrictions';

export type ConfidenceRating = 'A' | 'B' | 'C' | 'D';
export type RegimeTag = 'aden_irg' | 'sanaa_defacto' | 'mixed' | 'unknown';
export type Frequency = 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annual';
export type GeoLevel = 'national' | 'governorate' | 'district' | 'city';

export interface IndicatorDefinition {
  code: string;
  nameEn: string;
  nameAr: string;
  descriptionEn: string;
  descriptionAr: string;
  family: IndicatorFamily;
  unit: string;
  frequency: Frequency;
  geoLevel: GeoLevel;
  splitSystem: boolean; // Whether indicator differs by regime
  baseYear?: number;
  methodology?: string;
  sources: string[];
  startYear: number;
  confidenceDefault: ConfidenceRating;
}

// ============================================================================
// FAMILY 1: MACRO & REAL ECONOMY
// ============================================================================

export const macroRealEconomyIndicators: IndicatorDefinition[] = [
  {
    code: 'gdp_nominal',
    nameEn: 'Nominal GDP',
    nameAr: 'الناتج المحلي الإجمالي الاسمي',
    descriptionEn: 'Gross Domestic Product at current prices',
    descriptionAr: 'الناتج المحلي الإجمالي بالأسعار الجارية',
    family: 'macro_real_economy',
    unit: 'YER billions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    baseYear: 2015,
    methodology: 'Expenditure approach where available; production approach as alternative',
    sources: ['World Bank', 'IMF', 'CSO Yemen'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'gdp_real',
    nameEn: 'Real GDP',
    nameAr: 'الناتج المحلي الإجمالي الحقيقي',
    descriptionEn: 'Gross Domestic Product at constant 2015 prices',
    descriptionAr: 'الناتج المحلي الإجمالي بأسعار 2015 الثابتة',
    family: 'macro_real_economy',
    unit: 'YER billions (2015)',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    baseYear: 2015,
    methodology: 'Deflated using GDP deflator with 2015 base year',
    sources: ['World Bank', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'gdp_per_capita',
    nameEn: 'GDP per Capita',
    nameAr: 'نصيب الفرد من الناتج المحلي',
    descriptionEn: 'GDP per capita in current USD',
    descriptionAr: 'نصيب الفرد من الناتج المحلي بالدولار الأمريكي',
    family: 'macro_real_economy',
    unit: 'USD',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'GDP divided by mid-year population estimate',
    sources: ['World Bank', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'gdp_growth',
    nameEn: 'Real GDP Growth Rate',
    nameAr: 'معدل نمو الناتج المحلي الحقيقي',
    descriptionEn: 'Annual percentage change in real GDP',
    descriptionAr: 'التغير السنوي في الناتج المحلي الحقيقي',
    family: 'macro_real_economy',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'YoY change: (GDP_t / GDP_{t-1} - 1) * 100',
    sources: ['World Bank', 'IMF'],
    startYear: 2011,
    confidenceDefault: 'C',
  },
  {
    code: 'population',
    nameEn: 'Total Population',
    nameAr: 'إجمالي السكان',
    descriptionEn: 'Total population estimate',
    descriptionAr: 'تقدير إجمالي السكان',
    family: 'macro_real_economy',
    unit: 'millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'UN Population Division estimates; census-based projections',
    sources: ['UN Population Division', 'World Bank', 'CSO Yemen'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'population_governorate',
    nameEn: 'Population by Governorate',
    nameAr: 'السكان حسب المحافظة',
    descriptionEn: 'Population by governorate',
    descriptionAr: 'عدد السكان حسب المحافظة',
    family: 'macro_real_economy',
    unit: 'thousands',
    frequency: 'annual',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'Census-based projections with displacement adjustments',
    sources: ['CSO Yemen', 'UN OCHA'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'unemployment_rate',
    nameEn: 'Unemployment Rate',
    nameAr: 'معدل البطالة',
    descriptionEn: 'Percentage of labor force unemployed',
    descriptionAr: 'نسبة القوى العاملة العاطلة عن العمل',
    family: 'macro_real_economy',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'ILO definition; labor force surveys where available',
    sources: ['ILO', 'World Bank', 'CSO Yemen'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'labor_force_participation',
    nameEn: 'Labor Force Participation Rate',
    nameAr: 'معدل المشاركة في القوى العاملة',
    descriptionEn: 'Labor force as percentage of working-age population',
    descriptionAr: 'نسبة القوى العاملة من السكان في سن العمل',
    family: 'macro_real_economy',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'ILO definition; ages 15-64',
    sources: ['ILO', 'World Bank'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
];

// ============================================================================
// FAMILY 2: PRICES & COST OF LIVING
// ============================================================================

export const pricesCostOfLivingIndicators: IndicatorDefinition[] = [
  {
    code: 'cpi_national',
    nameEn: 'Consumer Price Index (National)',
    nameAr: 'مؤشر أسعار المستهلك (وطني)',
    descriptionEn: 'Consumer Price Index, national average',
    descriptionAr: 'مؤشر أسعار المستهلك، المتوسط الوطني',
    family: 'prices_cost_of_living',
    unit: 'index (2015=100)',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    baseYear: 2015,
    methodology: 'Laspeyres index with 2015 base weights',
    sources: ['CSO Yemen', 'World Bank'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'cpi_governorate',
    nameEn: 'Consumer Price Index (Governorate)',
    nameAr: 'مؤشر أسعار المستهلك (محافظة)',
    descriptionEn: 'Consumer Price Index by governorate',
    descriptionAr: 'مؤشر أسعار المستهلك حسب المحافظة',
    family: 'prices_cost_of_living',
    unit: 'index (2015=100)',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: true,
    baseYear: 2015,
    methodology: 'Governorate-level CPI where available',
    sources: ['CSO Yemen', 'WFP'],
    startYear: 2015,
    confidenceDefault: 'C',
  },
  {
    code: 'inflation_yoy',
    nameEn: 'Inflation Rate (YoY)',
    nameAr: 'معدل التضخم (سنوي)',
    descriptionEn: 'Year-over-year change in CPI',
    descriptionAr: 'التغير السنوي في مؤشر أسعار المستهلك',
    family: 'prices_cost_of_living',
    unit: 'percent',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'YoY: (CPI_t / CPI_{t-12} - 1) * 100',
    sources: ['CSO Yemen', 'World Bank'],
    startYear: 2011,
    confidenceDefault: 'B',
  },
  {
    code: 'inflation_mom',
    nameEn: 'Inflation Rate (MoM)',
    nameAr: 'معدل التضخم (شهري)',
    descriptionEn: 'Month-over-month change in CPI',
    descriptionAr: 'التغير الشهري في مؤشر أسعار المستهلك',
    family: 'prices_cost_of_living',
    unit: 'percent',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'MoM: (CPI_t / CPI_{t-1} - 1) * 100',
    sources: ['CSO Yemen', 'World Bank'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'food_price_index',
    nameEn: 'Food Price Index',
    nameAr: 'مؤشر أسعار الغذاء',
    descriptionEn: 'Food component of CPI',
    descriptionAr: 'مكون الغذاء في مؤشر أسعار المستهلك',
    family: 'prices_cost_of_living',
    unit: 'index (2015=100)',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    baseYear: 2015,
    methodology: 'Food basket weighted index',
    sources: ['WFP', 'CSO Yemen'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'wheat_flour_price',
    nameEn: 'Wheat Flour Price',
    nameAr: 'سعر دقيق القمح',
    descriptionEn: 'Retail price of wheat flour per 50kg',
    descriptionAr: 'سعر التجزئة لدقيق القمح لكل 50 كجم',
    family: 'prices_cost_of_living',
    unit: 'YER/50kg',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'WFP market monitoring; average of surveyed markets',
    sources: ['WFP VAM'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'rice_price',
    nameEn: 'Rice Price',
    nameAr: 'سعر الأرز',
    descriptionEn: 'Retail price of rice per kg',
    descriptionAr: 'سعر التجزئة للأرز لكل كجم',
    family: 'prices_cost_of_living',
    unit: 'YER/kg',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'WFP market monitoring',
    sources: ['WFP VAM'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'cooking_oil_price',
    nameEn: 'Cooking Oil Price',
    nameAr: 'سعر زيت الطهي',
    descriptionEn: 'Retail price of cooking oil per liter',
    descriptionAr: 'سعر التجزئة لزيت الطهي لكل لتر',
    family: 'prices_cost_of_living',
    unit: 'YER/liter',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'WFP market monitoring',
    sources: ['WFP VAM'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'sugar_price',
    nameEn: 'Sugar Price',
    nameAr: 'سعر السكر',
    descriptionEn: 'Retail price of sugar per kg',
    descriptionAr: 'سعر التجزئة للسكر لكل كجم',
    family: 'prices_cost_of_living',
    unit: 'YER/kg',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'WFP market monitoring',
    sources: ['WFP VAM'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'meb_cost',
    nameEn: 'Minimum Expenditure Basket Cost',
    nameAr: 'تكلفة سلة الإنفاق الأدنى',
    descriptionEn: 'Cost of minimum expenditure basket for household of 7',
    descriptionAr: 'تكلفة سلة الإنفاق الأدنى لأسرة مكونة من 7 أفراد',
    family: 'prices_cost_of_living',
    unit: 'YER/month',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'OCHA/WFP MEB methodology; includes food and non-food items',
    sources: ['WFP', 'OCHA'],
    startYear: 2017,
    confidenceDefault: 'A',
  },
  {
    code: 'fuel_petrol_price',
    nameEn: 'Petrol Price',
    nameAr: 'سعر البنزين',
    descriptionEn: 'Retail price of petrol per liter',
    descriptionAr: 'سعر التجزئة للبنزين لكل لتر',
    family: 'prices_cost_of_living',
    unit: 'YER/liter',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'Market monitoring; official and black market prices',
    sources: ['WFP', 'Local sources'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'fuel_diesel_price',
    nameEn: 'Diesel Price',
    nameAr: 'سعر الديزل',
    descriptionEn: 'Retail price of diesel per liter',
    descriptionAr: 'سعر التجزئة للديزل لكل لتر',
    family: 'prices_cost_of_living',
    unit: 'YER/liter',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'Market monitoring; official and black market prices',
    sources: ['WFP', 'Local sources'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'lpg_price',
    nameEn: 'LPG (Cooking Gas) Price',
    nameAr: 'سعر غاز الطهي',
    descriptionEn: 'Retail price of LPG cylinder',
    descriptionAr: 'سعر التجزئة لأسطوانة غاز الطهي',
    family: 'prices_cost_of_living',
    unit: 'YER/cylinder',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'Market monitoring',
    sources: ['WFP', 'Local sources'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'water_price',
    nameEn: 'Water Price (Trucked)',
    nameAr: 'سعر المياه (صهاريج)',
    descriptionEn: 'Price of trucked water per cubic meter',
    descriptionAr: 'سعر المياه المنقولة بالصهاريج لكل متر مكعب',
    family: 'prices_cost_of_living',
    unit: 'YER/m³',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'WASH cluster monitoring',
    sources: ['UNICEF', 'WASH Cluster'],
    startYear: 2017,
    confidenceDefault: 'B',
  },
];

// ============================================================================
// FAMILY 3: MONETARY & FINANCIAL SYSTEM (SPLIT SYSTEM)
// ============================================================================

export const monetaryFinancialIndicators: IndicatorDefinition[] = [
  {
    code: 'fx_rate_official',
    nameEn: 'Official Exchange Rate (USD/YER)',
    nameAr: 'سعر الصرف الرسمي (دولار/ريال)',
    descriptionEn: 'Official central bank exchange rate',
    descriptionAr: 'سعر الصرف الرسمي للبنك المركزي',
    family: 'monetary_financial',
    unit: 'YER per USD',
    frequency: 'daily',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Central bank published rate; differs by authority',
    sources: ['CBY Aden', 'CBY Sanaa'],
    startYear: 2010,
    confidenceDefault: 'A',
  },
  {
    code: 'fx_rate_market',
    nameEn: 'Market Exchange Rate (USD/YER)',
    nameAr: 'سعر الصرف السوقي (دولار/ريال)',
    descriptionEn: 'Parallel market exchange rate',
    descriptionAr: 'سعر الصرف في السوق الموازية',
    family: 'monetary_financial',
    unit: 'YER per USD',
    frequency: 'daily',
    geoLevel: 'governorate',
    splitSystem: true,
    methodology: 'Exchange bureau surveys; differs significantly by location',
    sources: ['Local exchange bureaus', 'WFP'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'fx_spread',
    nameEn: 'FX Spread (Official vs Market)',
    nameAr: 'فارق سعر الصرف',
    descriptionEn: 'Spread between official and market rates',
    descriptionAr: 'الفارق بين السعر الرسمي والسوقي',
    family: 'monetary_financial',
    unit: 'percent',
    frequency: 'daily',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'spread = (market_rate - official_rate) / official_rate * 100',
    sources: ['Derived'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'fx_divergence',
    nameEn: 'North-South FX Divergence',
    nameAr: 'تباين سعر الصرف شمال-جنوب',
    descriptionEn: 'Divergence between Aden and Sanaa market rates',
    descriptionAr: 'التباين بين أسعار السوق في عدن وصنعاء',
    family: 'monetary_financial',
    unit: 'percent',
    frequency: 'daily',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'divergence = abs(north - south) / min(north, south) * 100',
    sources: ['Derived'],
    startYear: 2016,
    confidenceDefault: 'B',
  },
  {
    code: 'fx_volatility_30d',
    nameEn: 'FX Volatility (30-day)',
    nameAr: 'تقلب سعر الصرف (30 يوم)',
    descriptionEn: '30-day rolling standard deviation of log returns',
    descriptionAr: 'الانحراف المعياري المتحرك لـ 30 يوم للعوائد اللوغاريتمية',
    family: 'monetary_financial',
    unit: 'percent',
    frequency: 'daily',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Rolling std of ln(rate_t / rate_{t-1}) over 30 days',
    sources: ['Derived'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'money_supply_m1',
    nameEn: 'Money Supply M1',
    nameAr: 'عرض النقود م1',
    descriptionEn: 'Narrow money supply (currency + demand deposits)',
    descriptionAr: 'عرض النقود الضيق (العملة + الودائع تحت الطلب)',
    family: 'monetary_financial',
    unit: 'YER billions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Central bank monetary statistics',
    sources: ['CBY Aden', 'CBY Sanaa', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'money_supply_m2',
    nameEn: 'Money Supply M2',
    nameAr: 'عرض النقود م2',
    descriptionEn: 'Broad money supply (M1 + time deposits)',
    descriptionAr: 'عرض النقود الواسع (م1 + الودائع لأجل)',
    family: 'monetary_financial',
    unit: 'YER billions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Central bank monetary statistics',
    sources: ['CBY Aden', 'CBY Sanaa', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'foreign_reserves',
    nameEn: 'Foreign Exchange Reserves',
    nameAr: 'احتياطيات النقد الأجنبي',
    descriptionEn: 'Central bank foreign exchange reserves',
    descriptionAr: 'احتياطيات البنك المركزي من النقد الأجنبي',
    family: 'monetary_financial',
    unit: 'USD millions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Central bank reported reserves',
    sources: ['CBY Aden', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'interest_rate_policy',
    nameEn: 'Policy Interest Rate',
    nameAr: 'سعر الفائدة الأساسي',
    descriptionEn: 'Central bank policy rate',
    descriptionAr: 'سعر الفائدة الأساسي للبنك المركزي',
    family: 'monetary_financial',
    unit: 'percent',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Central bank announced rate',
    sources: ['CBY Aden', 'CBY Sanaa'],
    startYear: 2010,
    confidenceDefault: 'A',
  },
  {
    code: 'bank_deposits_total',
    nameEn: 'Total Bank Deposits',
    nameAr: 'إجمالي الودائع المصرفية',
    descriptionEn: 'Total deposits in commercial banks',
    descriptionAr: 'إجمالي الودائع في البنوك التجارية',
    family: 'monetary_financial',
    unit: 'YER billions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Aggregated from bank reports',
    sources: ['CBY', 'Association of Yemeni Banks'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'bank_credit_private',
    nameEn: 'Private Sector Credit',
    nameAr: 'الائتمان للقطاع الخاص',
    descriptionEn: 'Bank credit to private sector',
    descriptionAr: 'الائتمان المصرفي للقطاع الخاص',
    family: 'monetary_financial',
    unit: 'YER billions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Central bank credit statistics',
    sources: ['CBY', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'remittances_inflow',
    nameEn: 'Remittance Inflows',
    nameAr: 'تحويلات المغتربين الواردة',
    descriptionEn: 'Personal remittances received',
    descriptionAr: 'التحويلات الشخصية الواردة',
    family: 'monetary_financial',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Balance of payments data; World Bank estimates',
    sources: ['World Bank', 'CBY'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
];

// ============================================================================
// FAMILY 4: PUBLIC FINANCE & GOVERNANCE
// ============================================================================

export const publicFinanceIndicators: IndicatorDefinition[] = [
  {
    code: 'gov_revenue_total',
    nameEn: 'Total Government Revenue',
    nameAr: 'إجمالي الإيرادات الحكومية',
    descriptionEn: 'Total government revenue including tax and non-tax',
    descriptionAr: 'إجمالي الإيرادات الحكومية شاملة الضريبية وغير الضريبية',
    family: 'public_finance',
    unit: 'YER billions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Ministry of Finance budget reports',
    sources: ['MoF Yemen', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'gov_revenue_tax',
    nameEn: 'Tax Revenue',
    nameAr: 'الإيرادات الضريبية',
    descriptionEn: 'Government tax revenue',
    descriptionAr: 'الإيرادات الضريبية الحكومية',
    family: 'public_finance',
    unit: 'YER billions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Tax authority reports',
    sources: ['MoF Yemen', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'gov_revenue_oil',
    nameEn: 'Oil Revenue',
    nameAr: 'إيرادات النفط',
    descriptionEn: 'Government revenue from oil and gas',
    descriptionAr: 'الإيرادات الحكومية من النفط والغاز',
    family: 'public_finance',
    unit: 'YER billions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Oil ministry and MoF reports',
    sources: ['MoF Yemen', 'Oil Ministry'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'gov_expenditure_total',
    nameEn: 'Total Government Expenditure',
    nameAr: 'إجمالي الإنفاق الحكومي',
    descriptionEn: 'Total government expenditure',
    descriptionAr: 'إجمالي الإنفاق الحكومي',
    family: 'public_finance',
    unit: 'YER billions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Ministry of Finance budget execution reports',
    sources: ['MoF Yemen', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'gov_expenditure_wages',
    nameEn: 'Government Wage Bill',
    nameAr: 'فاتورة الأجور الحكومية',
    descriptionEn: 'Government expenditure on wages and salaries',
    descriptionAr: 'الإنفاق الحكومي على الأجور والرواتب',
    family: 'public_finance',
    unit: 'YER billions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Budget execution data',
    sources: ['MoF Yemen'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'fiscal_balance',
    nameEn: 'Fiscal Balance',
    nameAr: 'الرصيد المالي',
    descriptionEn: 'Government fiscal balance (revenue - expenditure)',
    descriptionAr: 'الرصيد المالي الحكومي (الإيرادات - النفقات)',
    family: 'public_finance',
    unit: 'YER billions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Revenue minus expenditure',
    sources: ['MoF Yemen', 'IMF'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'fiscal_balance_gdp',
    nameEn: 'Fiscal Balance (% of GDP)',
    nameAr: 'الرصيد المالي (% من الناتج)',
    descriptionEn: 'Fiscal balance as percentage of GDP',
    descriptionAr: 'الرصيد المالي كنسبة من الناتج المحلي',
    family: 'public_finance',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Fiscal balance / GDP * 100',
    sources: ['IMF', 'World Bank'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'public_debt_total',
    nameEn: 'Total Public Debt',
    nameAr: 'إجمالي الدين العام',
    descriptionEn: 'Total government debt (domestic + external)',
    descriptionAr: 'إجمالي الدين الحكومي (محلي + خارجي)',
    family: 'public_finance',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'MoF and CBY debt statistics',
    sources: ['MoF Yemen', 'IMF', 'World Bank'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'public_debt_gdp',
    nameEn: 'Public Debt (% of GDP)',
    nameAr: 'الدين العام (% من الناتج)',
    descriptionEn: 'Public debt as percentage of GDP',
    descriptionAr: 'الدين العام كنسبة من الناتج المحلي',
    family: 'public_finance',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Total debt / GDP * 100',
    sources: ['IMF', 'World Bank'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'civil_servant_salary_payment',
    nameEn: 'Civil Servant Salary Payment Status',
    nameAr: 'حالة صرف رواتب الموظفين',
    descriptionEn: 'Status of civil servant salary payments (months in arrears)',
    descriptionAr: 'حالة صرف رواتب الموظفين الحكوميين (أشهر التأخير)',
    family: 'public_finance',
    unit: 'months',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Tracking salary payment delays by authority',
    sources: ['UN OCHA', 'Local reports'],
    startYear: 2016,
    confidenceDefault: 'B',
  },
];

// ============================================================================
// FAMILY 5: TRADE & EXTERNAL SECTOR
// ============================================================================

export const tradeExternalIndicators: IndicatorDefinition[] = [
  {
    code: 'exports_total',
    nameEn: 'Total Exports',
    nameAr: 'إجمالي الصادرات',
    descriptionEn: 'Total merchandise exports FOB',
    descriptionAr: 'إجمالي صادرات البضائع',
    family: 'trade_external',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Customs data; mirror trade statistics',
    sources: ['UN Comtrade', 'IMF DOTS', 'Customs'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'exports_oil',
    nameEn: 'Oil Exports',
    nameAr: 'صادرات النفط',
    descriptionEn: 'Crude oil and petroleum product exports',
    descriptionAr: 'صادرات النفط الخام والمنتجات البترولية',
    family: 'trade_external',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Oil ministry data; customs',
    sources: ['Oil Ministry', 'UN Comtrade'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'imports_total',
    nameEn: 'Total Imports',
    nameAr: 'إجمالي الواردات',
    descriptionEn: 'Total merchandise imports CIF',
    descriptionAr: 'إجمالي واردات البضائع',
    family: 'trade_external',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Customs data; mirror trade statistics',
    sources: ['UN Comtrade', 'IMF DOTS', 'Customs'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'imports_food',
    nameEn: 'Food Imports',
    nameAr: 'واردات الغذاء',
    descriptionEn: 'Food and agricultural product imports',
    descriptionAr: 'واردات الغذاء والمنتجات الزراعية',
    family: 'trade_external',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'HS codes 01-24; customs data',
    sources: ['UN Comtrade', 'FAO'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'imports_fuel',
    nameEn: 'Fuel Imports',
    nameAr: 'واردات الوقود',
    descriptionEn: 'Petroleum and fuel imports',
    descriptionAr: 'واردات البترول والوقود',
    family: 'trade_external',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'HS chapter 27; customs data',
    sources: ['UN Comtrade', 'Oil Ministry'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'trade_balance',
    nameEn: 'Trade Balance',
    nameAr: 'الميزان التجاري',
    descriptionEn: 'Exports minus imports',
    descriptionAr: 'الصادرات ناقص الواردات',
    family: 'trade_external',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Exports - Imports',
    sources: ['Derived'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'port_aden_throughput',
    nameEn: 'Port of Aden Throughput',
    nameAr: 'حركة ميناء عدن',
    descriptionEn: 'Container and cargo throughput at Aden port',
    descriptionAr: 'حركة الحاويات والبضائع في ميناء عدن',
    family: 'trade_external',
    unit: 'TEUs',
    frequency: 'monthly',
    geoLevel: 'city',
    splitSystem: true,
    methodology: 'Port authority statistics',
    sources: ['Aden Port Authority'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'port_hodeidah_throughput',
    nameEn: 'Port of Hodeidah Throughput',
    nameAr: 'حركة ميناء الحديدة',
    descriptionEn: 'Container and cargo throughput at Hodeidah port',
    descriptionAr: 'حركة الحاويات والبضائع في ميناء الحديدة',
    family: 'trade_external',
    unit: 'TEUs',
    frequency: 'monthly',
    geoLevel: 'city',
    splitSystem: true,
    methodology: 'Port authority statistics; UNVIM data',
    sources: ['UNVIM', 'Port Authority'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'fuel_imports_volume',
    nameEn: 'Fuel Import Volume',
    nameAr: 'حجم واردات الوقود',
    descriptionEn: 'Volume of fuel imports through ports',
    descriptionAr: 'حجم واردات الوقود عبر الموانئ',
    family: 'trade_external',
    unit: 'metric tons',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'UNVIM verification data',
    sources: ['UNVIM'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'food_imports_volume',
    nameEn: 'Food Import Volume',
    nameAr: 'حجم واردات الغذاء',
    descriptionEn: 'Volume of food imports through ports',
    descriptionAr: 'حجم واردات الغذاء عبر الموانئ',
    family: 'trade_external',
    unit: 'metric tons',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'UNVIM verification data',
    sources: ['UNVIM'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'current_account_balance',
    nameEn: 'Current Account Balance',
    nameAr: 'رصيد الحساب الجاري',
    descriptionEn: 'Balance of payments current account',
    descriptionAr: 'رصيد الحساب الجاري في ميزان المدفوعات',
    family: 'trade_external',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'IMF BOP statistics',
    sources: ['IMF', 'CBY'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
];

// ============================================================================
// FAMILY 6: HUMANITARIAN & SOCIAL OUTCOMES
// ============================================================================

export const humanitarianSocialIndicators: IndicatorDefinition[] = [
  {
    code: 'people_in_need',
    nameEn: 'People in Need',
    nameAr: 'الأشخاص المحتاجون',
    descriptionEn: 'Total people in need of humanitarian assistance',
    descriptionAr: 'إجمالي الأشخاص المحتاجين للمساعدات الإنسانية',
    family: 'humanitarian_social',
    unit: 'millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'OCHA HNO methodology',
    sources: ['OCHA'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'people_in_need_governorate',
    nameEn: 'People in Need by Governorate',
    nameAr: 'المحتاجون حسب المحافظة',
    descriptionEn: 'People in need by governorate',
    descriptionAr: 'الأشخاص المحتاجون حسب المحافظة',
    family: 'humanitarian_social',
    unit: 'thousands',
    frequency: 'annual',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'OCHA HNO methodology',
    sources: ['OCHA'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'food_insecurity_ipc3plus',
    nameEn: 'Food Insecurity (IPC 3+)',
    nameAr: 'انعدام الأمن الغذائي (IPC 3+)',
    descriptionEn: 'Population in IPC Phase 3 (Crisis) or above',
    descriptionAr: 'السكان في المرحلة 3 (أزمة) أو أعلى',
    family: 'humanitarian_social',
    unit: 'millions',
    frequency: 'quarterly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'IPC analysis',
    sources: ['IPC', 'WFP', 'FAO'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'acute_malnutrition_sam',
    nameEn: 'Severe Acute Malnutrition (SAM)',
    nameAr: 'سوء التغذية الحاد الوخيم',
    descriptionEn: 'Children under 5 with severe acute malnutrition',
    descriptionAr: 'الأطفال دون 5 سنوات المصابين بسوء التغذية الحاد الوخيم',
    family: 'humanitarian_social',
    unit: 'thousands',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'UNICEF/WHO standards; SMART surveys',
    sources: ['UNICEF', 'WHO', 'Nutrition Cluster'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'acute_malnutrition_mam',
    nameEn: 'Moderate Acute Malnutrition (MAM)',
    nameAr: 'سوء التغذية الحاد المعتدل',
    descriptionEn: 'Children under 5 with moderate acute malnutrition',
    descriptionAr: 'الأطفال دون 5 سنوات المصابين بسوء التغذية الحاد المعتدل',
    family: 'humanitarian_social',
    unit: 'thousands',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'UNICEF/WHO standards; SMART surveys',
    sources: ['UNICEF', 'WHO', 'Nutrition Cluster'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'idp_total',
    nameEn: 'Internally Displaced Persons',
    nameAr: 'النازحون داخلياً',
    descriptionEn: 'Total internally displaced persons',
    descriptionAr: 'إجمالي النازحين داخلياً',
    family: 'humanitarian_social',
    unit: 'millions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'IOM DTM methodology',
    sources: ['IOM DTM', 'UNHCR'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'idp_governorate',
    nameEn: 'IDPs by Governorate',
    nameAr: 'النازحون حسب المحافظة',
    descriptionEn: 'IDPs by governorate of displacement',
    descriptionAr: 'النازحون حسب محافظة النزوح',
    family: 'humanitarian_social',
    unit: 'thousands',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'IOM DTM methodology',
    sources: ['IOM DTM'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'cholera_cases',
    nameEn: 'Cholera Cases',
    nameAr: 'حالات الكوليرا',
    descriptionEn: 'Suspected cholera cases',
    descriptionAr: 'حالات الكوليرا المشتبه بها',
    family: 'humanitarian_social',
    unit: 'cases',
    frequency: 'weekly',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'WHO/MoPH surveillance',
    sources: ['WHO', 'MoPH Yemen'],
    startYear: 2016,
    confidenceDefault: 'A',
  },
  {
    code: 'health_facilities_functional',
    nameEn: 'Functional Health Facilities',
    nameAr: 'المرافق الصحية العاملة',
    descriptionEn: 'Percentage of health facilities fully functional',
    descriptionAr: 'نسبة المرافق الصحية العاملة بالكامل',
    family: 'humanitarian_social',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'HeRAMS assessment',
    sources: ['WHO', 'Health Cluster'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'water_access_improved',
    nameEn: 'Access to Improved Water',
    nameAr: 'الوصول للمياه المحسنة',
    descriptionEn: 'Population with access to improved water sources',
    descriptionAr: 'السكان الذين لديهم وصول لمصادر مياه محسنة',
    family: 'humanitarian_social',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'WASH cluster assessments',
    sources: ['UNICEF', 'WASH Cluster'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'poverty_rate',
    nameEn: 'Poverty Rate',
    nameAr: 'معدل الفقر',
    descriptionEn: 'Population below national poverty line',
    descriptionAr: 'السكان تحت خط الفقر الوطني',
    family: 'humanitarian_social',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'World Bank estimates; household surveys',
    sources: ['World Bank', 'UNDP'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'school_enrollment_primary',
    nameEn: 'Primary School Enrollment',
    nameAr: 'الالتحاق بالتعليم الابتدائي',
    descriptionEn: 'Net enrollment rate in primary education',
    descriptionAr: 'معدل الالتحاق الصافي بالتعليم الابتدائي',
    family: 'humanitarian_social',
    unit: 'percent',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'UNESCO/MoE statistics',
    sources: ['UNESCO', 'MoE Yemen'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
];

// ============================================================================
// FAMILY 7: AID, PROJECTS, ACCOUNTABILITY
// ============================================================================

export const aidProjectsIndicators: IndicatorDefinition[] = [
  {
    code: 'humanitarian_funding_required',
    nameEn: 'Humanitarian Funding Required',
    nameAr: 'التمويل الإنساني المطلوب',
    descriptionEn: 'Total humanitarian funding requirements',
    descriptionAr: 'إجمالي متطلبات التمويل الإنساني',
    family: 'aid_projects',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'HRP requirements',
    sources: ['OCHA FTS'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'humanitarian_funding_received',
    nameEn: 'Humanitarian Funding Received',
    nameAr: 'التمويل الإنساني المستلم',
    descriptionEn: 'Total humanitarian funding received',
    descriptionAr: 'إجمالي التمويل الإنساني المستلم',
    family: 'aid_projects',
    unit: 'USD millions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'FTS reported contributions',
    sources: ['OCHA FTS'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'humanitarian_funding_gap',
    nameEn: 'Humanitarian Funding Gap',
    nameAr: 'فجوة التمويل الإنساني',
    descriptionEn: 'Difference between required and received funding',
    descriptionAr: 'الفرق بين التمويل المطلوب والمستلم',
    family: 'aid_projects',
    unit: 'USD millions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Required - Received',
    sources: ['Derived from OCHA FTS'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'humanitarian_funding_coverage',
    nameEn: 'Humanitarian Funding Coverage',
    nameAr: 'نسبة تغطية التمويل الإنساني',
    descriptionEn: 'Percentage of requirements funded',
    descriptionAr: 'نسبة المتطلبات الممولة',
    family: 'aid_projects',
    unit: 'percent',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Received / Required * 100',
    sources: ['Derived from OCHA FTS'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'development_oda',
    nameEn: 'Official Development Assistance',
    nameAr: 'المساعدة الإنمائية الرسمية',
    descriptionEn: 'Total ODA disbursements',
    descriptionAr: 'إجمالي صرفيات المساعدة الإنمائية الرسمية',
    family: 'aid_projects',
    unit: 'USD millions',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'OECD DAC statistics',
    sources: ['OECD DAC', 'IATI'],
    startYear: 2010,
    confidenceDefault: 'A',
  },
  {
    code: 'active_projects_count',
    nameEn: 'Active Development Projects',
    nameAr: 'المشاريع التنموية النشطة',
    descriptionEn: 'Number of active development projects',
    descriptionAr: 'عدد المشاريع التنموية النشطة',
    family: 'aid_projects',
    unit: 'count',
    frequency: 'quarterly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'IATI activity status',
    sources: ['IATI', 'World Bank'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'people_reached_humanitarian',
    nameEn: 'People Reached (Humanitarian)',
    nameAr: 'الأشخاص المستفيدون (إنساني)',
    descriptionEn: 'People reached with humanitarian assistance',
    descriptionAr: 'الأشخاص الذين وصلتهم المساعدات الإنسانية',
    family: 'aid_projects',
    unit: 'millions',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Cluster reporting',
    sources: ['OCHA'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'cash_transfer_value',
    nameEn: 'Cash Transfer Value',
    nameAr: 'قيمة التحويلات النقدية',
    descriptionEn: 'Average cash transfer value per household',
    descriptionAr: 'متوسط قيمة التحويل النقدي لكل أسرة',
    family: 'aid_projects',
    unit: 'USD',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'CWG reporting',
    sources: ['Cash Working Group', 'WFP'],
    startYear: 2017,
    confidenceDefault: 'A',
  },
  {
    code: 'transfer_value_adequacy',
    nameEn: 'Transfer Value Adequacy',
    nameAr: 'كفاية قيمة التحويل',
    descriptionEn: 'Cash transfer as percentage of MEB',
    descriptionAr: 'التحويل النقدي كنسبة من سلة الإنفاق الأدنى',
    family: 'aid_projects',
    unit: 'percent',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'cash_transfer_value / MEB_cost * 100',
    sources: ['Derived'],
    startYear: 2017,
    confidenceDefault: 'A',
  },
];

// ============================================================================
// FAMILY 8: CONFLICT & POLITICAL ECONOMY LINKAGES
// ============================================================================

export const conflictPoliticalIndicators: IndicatorDefinition[] = [
  {
    code: 'conflict_events',
    nameEn: 'Conflict Events',
    nameAr: 'أحداث النزاع',
    descriptionEn: 'Number of conflict events recorded',
    descriptionAr: 'عدد أحداث النزاع المسجلة',
    family: 'conflict_political',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'ACLED/UCDP event coding',
    sources: ['ACLED', 'UCDP'],
    startYear: 2015,
    confidenceDefault: 'A',
  },
  {
    code: 'conflict_fatalities',
    nameEn: 'Conflict Fatalities',
    nameAr: 'ضحايا النزاع',
    descriptionEn: 'Estimated fatalities from conflict',
    descriptionAr: 'الوفيات المقدرة من النزاع',
    family: 'conflict_political',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'ACLED/UCDP fatality estimates',
    sources: ['ACLED', 'UCDP'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'airstrikes',
    nameEn: 'Airstrikes',
    nameAr: 'الغارات الجوية',
    descriptionEn: 'Number of airstrikes recorded',
    descriptionAr: 'عدد الغارات الجوية المسجلة',
    family: 'conflict_political',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'YEMAC/ACLED tracking',
    sources: ['ACLED', 'Yemen Data Project'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'civilian_infrastructure_damage',
    nameEn: 'Civilian Infrastructure Damage',
    nameAr: 'أضرار البنية التحتية المدنية',
    descriptionEn: 'Incidents of civilian infrastructure damage',
    descriptionAr: 'حوادث أضرار البنية التحتية المدنية',
    family: 'conflict_political',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'governorate',
    splitSystem: false,
    methodology: 'UNOSAT/damage assessments',
    sources: ['UNOSAT', 'Yemen Data Project'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'territory_control',
    nameEn: 'Territory Control',
    nameAr: 'السيطرة الإقليمية',
    descriptionEn: 'Estimated territory under each authority',
    descriptionAr: 'الأراضي المقدرة تحت سيطرة كل سلطة',
    family: 'conflict_political',
    unit: 'percent',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Mapping from multiple sources',
    sources: ['Various'],
    startYear: 2015,
    confidenceDefault: 'C',
  },
  {
    code: 'ceasefire_violations',
    nameEn: 'Ceasefire Violations',
    nameAr: 'انتهاكات وقف إطلاق النار',
    descriptionEn: 'Reported ceasefire violations',
    descriptionAr: 'انتهاكات وقف إطلاق النار المبلغ عنها',
    family: 'conflict_political',
    unit: 'count',
    frequency: 'weekly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'UN monitoring',
    sources: ['UN Envoy Office'],
    startYear: 2022,
    confidenceDefault: 'B',
  },
];

// ============================================================================
// FAMILY 9: PRIVATE SECTOR & FIRMS (DOCUMENTED ONLY)
// ============================================================================

export const privateSectorIndicators: IndicatorDefinition[] = [
  {
    code: 'commercial_bank_count',
    nameEn: 'Number of Commercial Banks',
    nameAr: 'عدد البنوك التجارية',
    descriptionEn: 'Number of licensed commercial banks',
    descriptionAr: 'عدد البنوك التجارية المرخصة',
    family: 'private_sector',
    unit: 'count',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'CBY licensing records',
    sources: ['CBY', 'Association of Yemeni Banks'],
    startYear: 2010,
    confidenceDefault: 'A',
  },
  {
    code: 'mfi_count',
    nameEn: 'Number of Microfinance Institutions',
    nameAr: 'عدد مؤسسات التمويل الأصغر',
    descriptionEn: 'Number of licensed MFIs',
    descriptionAr: 'عدد مؤسسات التمويل الأصغر المرخصة',
    family: 'private_sector',
    unit: 'count',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Yemen Microfinance Network data',
    sources: ['Yemen Microfinance Network'],
    startYear: 2010,
    confidenceDefault: 'A',
  },
  {
    code: 'mfi_active_borrowers',
    nameEn: 'MFI Active Borrowers',
    nameAr: 'المقترضون النشطون من التمويل الأصغر',
    descriptionEn: 'Number of active MFI borrowers',
    descriptionAr: 'عدد المقترضين النشطين من مؤسسات التمويل الأصغر',
    family: 'private_sector',
    unit: 'thousands',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'Yemen Microfinance Network reporting',
    sources: ['Yemen Microfinance Network'],
    startYear: 2010,
    confidenceDefault: 'B',
  },
  {
    code: 'exchange_bureau_count',
    nameEn: 'Licensed Exchange Bureaus',
    nameAr: 'محلات الصرافة المرخصة',
    descriptionEn: 'Number of licensed exchange bureaus',
    descriptionAr: 'عدد محلات الصرافة المرخصة',
    family: 'private_sector',
    unit: 'count',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'CBY licensing records',
    sources: ['CBY'],
    startYear: 2015,
    confidenceDefault: 'B',
  },
  {
    code: 'business_registrations',
    nameEn: 'New Business Registrations',
    nameAr: 'تسجيلات الأعمال الجديدة',
    descriptionEn: 'Number of new business registrations',
    descriptionAr: 'عدد تسجيلات الأعمال الجديدة',
    family: 'private_sector',
    unit: 'count',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Ministry of Trade records',
    sources: ['Ministry of Trade'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
  {
    code: 'soe_count',
    nameEn: 'State-Owned Enterprises',
    nameAr: 'المؤسسات المملوكة للدولة',
    descriptionEn: 'Number of state-owned enterprises',
    descriptionAr: 'عدد المؤسسات المملوكة للدولة',
    family: 'private_sector',
    unit: 'count',
    frequency: 'annual',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Government records',
    sources: ['Government of Yemen'],
    startYear: 2010,
    confidenceDefault: 'C',
  },
];

// ============================================================================
// FAMILY 10: SANCTIONS/RESTRICTIONS CONTEXT (INFORMATIONAL ONLY)
// ============================================================================

export const sanctionsRestrictionsIndicators: IndicatorDefinition[] = [
  {
    code: 'un_sanctions_designations',
    nameEn: 'UN Sanctions Designations',
    nameAr: 'تعيينات عقوبات الأمم المتحدة',
    descriptionEn: 'Number of UN Security Council sanctions designations',
    descriptionAr: 'عدد تعيينات عقوبات مجلس الأمن الدولي',
    family: 'sanctions_restrictions',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'UN Security Council consolidated list',
    sources: ['UN Security Council'],
    startYear: 2014,
    confidenceDefault: 'A',
  },
  {
    code: 'us_ofac_designations',
    nameEn: 'US OFAC Designations',
    nameAr: 'تعيينات OFAC الأمريكية',
    descriptionEn: 'Number of US OFAC sanctions designations',
    descriptionAr: 'عدد تعيينات عقوبات OFAC الأمريكية',
    family: 'sanctions_restrictions',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'OFAC SDN list',
    sources: ['US Treasury OFAC'],
    startYear: 2014,
    confidenceDefault: 'A',
  },
  {
    code: 'eu_sanctions_designations',
    nameEn: 'EU Sanctions Designations',
    nameAr: 'تعيينات عقوبات الاتحاد الأوروبي',
    descriptionEn: 'Number of EU sanctions designations',
    descriptionAr: 'عدد تعيينات عقوبات الاتحاد الأوروبي',
    family: 'sanctions_restrictions',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'EU consolidated sanctions list',
    sources: ['EU Council'],
    startYear: 2014,
    confidenceDefault: 'A',
  },
  {
    code: 'uk_sanctions_designations',
    nameEn: 'UK Sanctions Designations',
    nameAr: 'تعيينات عقوبات المملكة المتحدة',
    descriptionEn: 'Number of UK sanctions designations',
    descriptionAr: 'عدد تعيينات عقوبات المملكة المتحدة',
    family: 'sanctions_restrictions',
    unit: 'count',
    frequency: 'monthly',
    geoLevel: 'national',
    splitSystem: false,
    methodology: 'UK OFSI consolidated list',
    sources: ['UK HM Treasury'],
    startYear: 2014,
    confidenceDefault: 'A',
  },
  {
    code: 'banking_restrictions_index',
    nameEn: 'Banking Restrictions Index',
    nameAr: 'مؤشر القيود المصرفية',
    descriptionEn: 'Composite index of banking sector restrictions',
    descriptionAr: 'مؤشر مركب للقيود على القطاع المصرفي',
    family: 'sanctions_restrictions',
    unit: 'index (0-100)',
    frequency: 'quarterly',
    geoLevel: 'national',
    splitSystem: true,
    methodology: 'Composite of correspondent banking, SWIFT access, etc.',
    sources: ['Various'],
    startYear: 2015,
    confidenceDefault: 'C',
  },
];

// ============================================================================
// COMBINED CATALOG
// ============================================================================

export const allIndicators: IndicatorDefinition[] = [
  ...macroRealEconomyIndicators,
  ...pricesCostOfLivingIndicators,
  ...monetaryFinancialIndicators,
  ...publicFinanceIndicators,
  ...tradeExternalIndicators,
  ...humanitarianSocialIndicators,
  ...aidProjectsIndicators,
  ...conflictPoliticalIndicators,
  ...privateSectorIndicators,
  ...sanctionsRestrictionsIndicators,
];

export const indicatorFamilies: { id: IndicatorFamily; nameEn: string; nameAr: string; count: number }[] = [
  { id: 'macro_real_economy', nameEn: 'Macro & Real Economy', nameAr: 'الاقتصاد الكلي والحقيقي', count: macroRealEconomyIndicators.length },
  { id: 'prices_cost_of_living', nameEn: 'Prices & Cost of Living', nameAr: 'الأسعار وتكاليف المعيشة', count: pricesCostOfLivingIndicators.length },
  { id: 'monetary_financial', nameEn: 'Monetary & Financial System', nameAr: 'النظام النقدي والمالي', count: monetaryFinancialIndicators.length },
  { id: 'public_finance', nameEn: 'Public Finance & Governance', nameAr: 'المالية العامة والحوكمة', count: publicFinanceIndicators.length },
  { id: 'trade_external', nameEn: 'Trade & External Sector', nameAr: 'التجارة والقطاع الخارجي', count: tradeExternalIndicators.length },
  { id: 'humanitarian_social', nameEn: 'Humanitarian & Social Outcomes', nameAr: 'النتائج الإنسانية والاجتماعية', count: humanitarianSocialIndicators.length },
  { id: 'aid_projects', nameEn: 'Aid, Projects, Accountability', nameAr: 'المساعدات والمشاريع والمساءلة', count: aidProjectsIndicators.length },
  { id: 'conflict_political', nameEn: 'Conflict & Political Economy', nameAr: 'النزاع والاقتصاد السياسي', count: conflictPoliticalIndicators.length },
  { id: 'private_sector', nameEn: 'Private Sector & Firms', nameAr: 'القطاع الخاص والشركات', count: privateSectorIndicators.length },
  { id: 'sanctions_restrictions', nameEn: 'Sanctions/Restrictions Context', nameAr: 'سياق العقوبات والقيود', count: sanctionsRestrictionsIndicators.length },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getIndicatorByCode(code: string): IndicatorDefinition | undefined {
  return allIndicators.find(i => i.code === code);
}

export function getIndicatorsByFamily(family: IndicatorFamily): IndicatorDefinition[] {
  return allIndicators.filter(i => i.family === family);
}

export function getIndicatorsBySplitSystem(splitSystem: boolean): IndicatorDefinition[] {
  return allIndicators.filter(i => i.splitSystem === splitSystem);
}

export function getIndicatorsByFrequency(frequency: Frequency): IndicatorDefinition[] {
  return allIndicators.filter(i => i.frequency === frequency);
}

export function getIndicatorsByGeoLevel(geoLevel: GeoLevel): IndicatorDefinition[] {
  return allIndicators.filter(i => i.geoLevel === geoLevel);
}

export function searchIndicators(query: string): IndicatorDefinition[] {
  const lowerQuery = query.toLowerCase();
  return allIndicators.filter(i => 
    i.code.toLowerCase().includes(lowerQuery) ||
    i.nameEn.toLowerCase().includes(lowerQuery) ||
    i.nameAr.includes(query) ||
    i.descriptionEn.toLowerCase().includes(lowerQuery) ||
    i.descriptionAr.includes(query)
  );
}

export const INDICATOR_CATALOG_STATS = {
  totalIndicators: allIndicators.length,
  families: indicatorFamilies.length,
  splitSystemIndicators: allIndicators.filter(i => i.splitSystem).length,
  dailyIndicators: allIndicators.filter(i => i.frequency === 'daily').length,
  weeklyIndicators: allIndicators.filter(i => i.frequency === 'weekly').length,
  monthlyIndicators: allIndicators.filter(i => i.frequency === 'monthly').length,
  quarterlyIndicators: allIndicators.filter(i => i.frequency === 'quarterly').length,
  annualIndicators: allIndicators.filter(i => i.frequency === 'annual').length,
  governorateLevelIndicators: allIndicators.filter(i => i.geoLevel === 'governorate').length,
};
