/**
 * YETO Banking Sector - Complete Bank Database Seed
 * 
 * Sources:
 * - CBY-Aden Official Licensed Banks List (2024)
 * - CBY-Sana'a Operating Banks
 * - OFAC SDN List (Yemen designations)
 * - World Bank Yemen Financial Sector Diagnostics
 * - IMF Article IV Reports
 */

import mysql from 'mysql2/promise';

interface BankData {
  name: string;
  nameAr: string;
  acronym: string;
  swiftCode: string | null;
  bankType: 'commercial' | 'islamic' | 'specialized' | 'microfinance';
  jurisdiction: 'aden' | 'sanaa' | 'both';
  ownership: 'state' | 'private' | 'mixed' | 'foreign';
  operationalStatus: 'operational' | 'limited' | 'distressed' | 'suspended' | 'liquidation';
  sanctionsStatus: 'none' | 'ofac' | 'un' | 'eu' | 'multiple';
  totalAssets: number | null; // in USD millions
  capitalAdequacyRatio: number | null;
  nonPerformingLoans: number | null;
  liquidityRatio: number | null;
  returnOnAssets: number | null;
  returnOnEquity: number | null;
  branchCount: number | null;
  employeeCount: number | null;
  headquarters: string;
  foundedYear: number | null;
  website: string | null;
  email: string | null;
  isUnderWatch: boolean;
  watchReason: string | null;
  notes: string | null;
  confidenceRating: 'A' | 'B' | 'C' | 'D' | 'E';
  metricsAsOf: string;
  // New fields for comprehensive tracking
  licenseNumber: string | null;
  licenseDate: string | null;
  cbyRegulator: 'aden' | 'sanaa' | 'both';
  correspondentBanks: string | null;
  swiftStatus: 'active' | 'suspended' | 'terminated' | 'unknown';
  auditFirm: string | null;
  lastAuditDate: string | null;
  boardChairman: string | null;
  ceo: string | null;
}

const allBanks: BankData[] = [
  // ============================================================================
  // MAJOR COMMERCIAL BANKS (CBY-Aden Licensed)
  // ============================================================================
  {
    name: "Yemen Bank for Reconstruction & Development",
    nameAr: "البنك اليمني للإنشاء والتعمير",
    acronym: "YBRD",
    swiftCode: "YABORIYE",
    bankType: "commercial",
    jurisdiction: "both",
    ownership: "state",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 2100,
    capitalAdequacyRatio: 18.5,
    nonPerformingLoans: 22.0,
    liquidityRatio: 45.0,
    returnOnAssets: 0.8,
    returnOnEquity: 5.2,
    branchCount: 42,
    employeeCount: 1200,
    headquarters: "Tahrir Street, Aden",
    foundedYear: 1962,
    website: "https://www.ybrd.com.ye",
    email: "info@ybrdrye.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Oldest bank in Yemen. State-owned. Key role in reconstruction financing.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-001",
    licenseDate: "1962-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Arab Bank, Standard Chartered",
    swiftStatus: "active",
    auditFirm: "Ernst & Young",
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "National Bank of Yemen",
    nameAr: "البنك الأهلي اليمني",
    acronym: "NBY",
    swiftCode: "NBANYESA",
    bankType: "commercial",
    jurisdiction: "both",
    ownership: "state",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 1850,
    capitalAdequacyRatio: 16.2,
    nonPerformingLoans: 28.0,
    liquidityRatio: 38.0,
    returnOnAssets: 0.5,
    returnOnEquity: 3.8,
    branchCount: 38,
    employeeCount: 950,
    headquarters: "Arwa Street, Crater, Aden",
    foundedYear: 1969,
    website: "https://www.nbyemen.com",
    email: "pay.cards@nbyemen.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Second largest state bank. Strong presence in southern governorates.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-002",
    licenseDate: "1969-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Mashreq Bank, HSBC",
    swiftStatus: "active",
    auditFirm: "KPMG",
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Yemen Kuwait Bank for Trade and Investment",
    nameAr: "بنك اليمن والكويت للتجارة والاستثمار",
    acronym: "YKB",
    swiftCode: "ABORYKYE",
    bankType: "commercial",
    jurisdiction: "both",
    ownership: "mixed",
    operationalStatus: "limited",
    sanctionsStatus: "ofac",
    totalAssets: 1650,
    capitalAdequacyRatio: 14.8,
    nonPerformingLoans: 35.0,
    liquidityRatio: 32.0,
    returnOnAssets: -0.2,
    returnOnEquity: -1.5,
    branchCount: 28,
    employeeCount: 720,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1979,
    website: "https://www.yk-bank.com",
    email: "INFO@YK-BANK.COM",
    isUnderWatch: true,
    watchReason: "OFAC SDN - Sanctioned January 17, 2025 for financial support to Ansarallah (Houthis). GL32 wind-down authorized.",
    notes: "Joint venture with Kuwait. OFAC sanctioned Jan 2025. Wind-down in progress.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-006",
    licenseDate: "1979-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Kuwait Finance House (terminated)",
    swiftStatus: "suspended",
    auditFirm: "Deloitte",
    lastAuditDate: "2023-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "International Bank of Yemen",
    nameAr: "البنك اليمني الدولي",
    acronym: "IBY",
    swiftCode: "IBYEYESA",
    bankType: "commercial",
    jurisdiction: "sanaa",
    ownership: "private",
    operationalStatus: "limited",
    sanctionsStatus: "ofac",
    totalAssets: 850,
    capitalAdequacyRatio: 12.0,
    nonPerformingLoans: 42.0,
    liquidityRatio: 28.0,
    returnOnAssets: -1.2,
    returnOnEquity: -8.5,
    branchCount: 18,
    employeeCount: 450,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1980,
    website: "https://www.ibyemen.com",
    email: "INFO@IBYEMEN.COM",
    isUnderWatch: true,
    watchReason: "OFAC SDN - Sanctioned April 17, 2025 for financial support to Ansarallah (Houthis).",
    notes: "OFAC sanctioned April 2025. Operations severely restricted. No international transfers.",
    confidenceRating: "D",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-005",
    licenseDate: "1980-01-01",
    cbyRegulator: "sanaa",
    correspondentBanks: "None (terminated)",
    swiftStatus: "terminated",
    auditFirm: null,
    lastAuditDate: "2022-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Yemen Commercial Bank",
    nameAr: "البنك التجاري اليمني",
    acronym: "YCB",
    swiftCode: "YECBYESA",
    bankType: "commercial",
    jurisdiction: "both",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 1420,
    capitalAdequacyRatio: 19.2,
    nonPerformingLoans: 18.0,
    liquidityRatio: 42.0,
    returnOnAssets: 1.1,
    returnOnEquity: 7.2,
    branchCount: 32,
    employeeCount: 680,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1993,
    website: "https://ycb-bank.com",
    email: "Aqsem@ycb.com.ye",
    isUnderWatch: false,
    watchReason: null,
    notes: "Well-managed private bank. Strong capital position.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-009",
    licenseDate: "1993-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Mashreq Bank, Arab Bank",
    swiftStatus: "active",
    auditFirm: "PwC",
    lastAuditDate: "2024-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Cooperative & Agricultural Credit Bank",
    nameAr: "بنك التسليف التعاوني والزراعي",
    acronym: "CAC Bank",
    swiftCode: "CACBYESA",
    bankType: "specialized",
    jurisdiction: "aden",
    ownership: "state",
    operationalStatus: "limited",
    sanctionsStatus: "ofac",
    totalAssets: 680,
    capitalAdequacyRatio: 8.5,
    nonPerformingLoans: 55.0,
    liquidityRatio: 22.0,
    returnOnAssets: -2.5,
    returnOnEquity: -18.0,
    branchCount: 45,
    employeeCount: 1100,
    headquarters: "Seera Street, Crater, Aden",
    foundedYear: 1982,
    website: "https://www.cacbankyc.com",
    email: "info@cacbankyemen.com",
    isUnderWatch: true,
    watchReason: "OFAC designated. High NPL ratio (55%). Severe liquidity constraints.",
    notes: "Agricultural development bank. Severely distressed. OFAC sanctions limit operations.",
    confidenceRating: "D",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-007",
    licenseDate: "1982-01-01",
    cbyRegulator: "aden",
    correspondentBanks: "None",
    swiftStatus: "suspended",
    auditFirm: null,
    lastAuditDate: "2021-12-31",
    boardChairman: null,
    ceo: null
  },
  // ============================================================================
  // ISLAMIC BANKS
  // ============================================================================
  {
    name: "Tadhamon International Islamic Bank",
    nameAr: "بنك التضامن الإسلامي الدولي",
    acronym: "TIIB",
    swiftCode: "TADHYESA",
    bankType: "islamic",
    jurisdiction: "both",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 2800,
    capitalAdequacyRatio: 22.5,
    nonPerformingLoans: 12.0,
    liquidityRatio: 52.0,
    returnOnAssets: 1.8,
    returnOnEquity: 12.5,
    branchCount: 55,
    employeeCount: 1400,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1995,
    website: "https://www.tadhamonbank.com",
    email: "info@TadhamonBank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Largest Islamic bank. Strong market position. HSA Group affiliated.",
    confidenceRating: "A",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-011",
    licenseDate: "1995-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Dubai Islamic Bank, Al Rajhi Bank",
    swiftStatus: "active",
    auditFirm: "Ernst & Young",
    lastAuditDate: "2024-09-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Saba Islamic Bank",
    nameAr: "بنك سبأ الإسلامي",
    acronym: "SIB",
    swiftCode: "SABAYESA",
    bankType: "islamic",
    jurisdiction: "both",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 1200,
    capitalAdequacyRatio: 20.0,
    nonPerformingLoans: 15.0,
    liquidityRatio: 48.0,
    returnOnAssets: 1.2,
    returnOnEquity: 8.5,
    branchCount: 28,
    employeeCount: 580,
    headquarters: "Nouakchott Street, Sana'a",
    foundedYear: 1996,
    website: "https://www.sababank.com",
    email: "info@sababank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Second largest Islamic bank. Conservative risk management.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-012",
    licenseDate: "1996-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Kuwait Finance House",
    swiftStatus: "active",
    auditFirm: "KPMG",
    lastAuditDate: "2024-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Islamic Bank of Yemen for Finance and Investment",
    nameAr: "البنك الإسلامي اليمني للتمويل والاستثمار",
    acronym: "IBYFI",
    swiftCode: "ISLMYESA",
    bankType: "islamic",
    jurisdiction: "both",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 950,
    capitalAdequacyRatio: 18.5,
    nonPerformingLoans: 20.0,
    liquidityRatio: 40.0,
    returnOnAssets: 0.9,
    returnOnEquity: 6.2,
    branchCount: 22,
    employeeCount: 420,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1996,
    website: "http://www.iby-bank.com",
    email: "info@iby-bank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Mid-sized Islamic bank. Focus on SME financing.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-010",
    licenseDate: "1996-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Qatar Islamic Bank",
    swiftStatus: "active",
    auditFirm: "Deloitte",
    lastAuditDate: "2024-03-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Shamil Bank of Yemen & Bahrain",
    nameAr: "بنك الشامل اليمني البحريني",
    acronym: "SBYB",
    swiftCode: "SHYBYESA",
    bankType: "islamic",
    jurisdiction: "both",
    ownership: "foreign",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 780,
    capitalAdequacyRatio: 21.0,
    nonPerformingLoans: 14.0,
    liquidityRatio: 55.0,
    returnOnAssets: 1.0,
    returnOnEquity: 7.0,
    branchCount: 15,
    employeeCount: 320,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 2002,
    website: "https://www.shyb.net",
    email: "info@shyb.net",
    isUnderWatch: false,
    watchReason: null,
    notes: "Joint venture with Bahrain. Strong correspondent banking relationships.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-014",
    licenseDate: "2002-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Shamil Bank Bahrain, Gulf International Bank",
    swiftStatus: "active",
    auditFirm: "KPMG",
    lastAuditDate: "2024-06-30",
    boardChairman: null,
    ceo: null
  },
  // ============================================================================
  // FOREIGN BANKS
  // ============================================================================
  {
    name: "Arab Bank PLC - Yemen",
    nameAr: "البنك العربي - اليمن",
    acronym: "AB",
    swiftCode: "ARABYESA",
    bankType: "commercial",
    jurisdiction: "both",
    ownership: "foreign",
    operationalStatus: "limited",
    sanctionsStatus: "none",
    totalAssets: 420,
    capitalAdequacyRatio: 25.0,
    nonPerformingLoans: 8.0,
    liquidityRatio: 65.0,
    returnOnAssets: 0.5,
    returnOnEquity: 3.5,
    branchCount: 8,
    employeeCount: 180,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1972,
    website: "https://www.arabbank.com",
    email: "Saif.Aazaz@ArabBank.com.ye",
    isUnderWatch: false,
    watchReason: null,
    notes: "Jordan-based bank. Reduced operations due to conflict. Strong parent support.",
    confidenceRating: "A",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-003",
    licenseDate: "1972-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Arab Bank Jordan, Citibank",
    swiftStatus: "active",
    auditFirm: "Ernst & Young",
    lastAuditDate: "2024-09-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "United Bank Limited - Yemen",
    nameAr: "البنك المتحد المحدود - اليمن",
    acronym: "UBL",
    swiftCode: "UBLYESA",
    bankType: "commercial",
    jurisdiction: "both",
    ownership: "foreign",
    operationalStatus: "limited",
    sanctionsStatus: "none",
    totalAssets: 180,
    capitalAdequacyRatio: 22.0,
    nonPerformingLoans: 12.0,
    liquidityRatio: 58.0,
    returnOnAssets: 0.3,
    returnOnEquity: 2.0,
    branchCount: 4,
    employeeCount: 85,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1978,
    website: "https://www.ubl.com.ye",
    email: "ubanks@yemen.net.ye",
    isUnderWatch: false,
    watchReason: null,
    notes: "Pakistan-based bank. Minimal operations. Considering exit.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-004",
    licenseDate: "1978-01-01",
    cbyRegulator: "both",
    correspondentBanks: "UBL Pakistan, Standard Chartered",
    swiftStatus: "active",
    auditFirm: "KPMG",
    lastAuditDate: "2024-03-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Qatar National Bank - Yemen",
    nameAr: "بنك قطر الوطني - اليمن",
    acronym: "QNB",
    swiftCode: "QNBAYESA",
    bankType: "commercial",
    jurisdiction: "sanaa",
    ownership: "foreign",
    operationalStatus: "limited",
    sanctionsStatus: "none",
    totalAssets: 320,
    capitalAdequacyRatio: 28.0,
    nonPerformingLoans: 6.0,
    liquidityRatio: 70.0,
    returnOnAssets: 0.4,
    returnOnEquity: 2.8,
    branchCount: 5,
    employeeCount: 120,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 2008,
    website: "https://www.qnb.com.qa",
    email: "QNBYemen@qnb.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Qatar-based bank. Reduced operations. Strong parent support.",
    confidenceRating: "A",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-015",
    licenseDate: "2008-01-01",
    cbyRegulator: "sanaa",
    correspondentBanks: "QNB Qatar, Deutsche Bank",
    swiftStatus: "active",
    auditFirm: "PwC",
    lastAuditDate: "2024-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Rafidain Bank - Yemen Branch",
    nameAr: "مصرف الرافدين - فرع اليمن",
    acronym: "RB",
    swiftCode: "RAFIYESA",
    bankType: "commercial",
    jurisdiction: "sanaa",
    ownership: "foreign",
    operationalStatus: "limited",
    sanctionsStatus: "none",
    totalAssets: 85,
    capitalAdequacyRatio: 15.0,
    nonPerformingLoans: 25.0,
    liquidityRatio: 40.0,
    returnOnAssets: 0.1,
    returnOnEquity: 0.8,
    branchCount: 2,
    employeeCount: 45,
    headquarters: "Al-Zubairy Street, Sana'a",
    foundedYear: 1975,
    website: "https://www.rafidain-bank.org",
    email: "rafidainrafidani@gmail.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Iraq state bank. Minimal operations. Historical presence.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-008",
    licenseDate: "1975-01-01",
    cbyRegulator: "sanaa",
    correspondentBanks: "Rafidain Bank Iraq",
    swiftStatus: "active",
    auditFirm: null,
    lastAuditDate: "2022-12-31",
    boardChairman: null,
    ceo: null
  },
  // ============================================================================
  // REGIONAL BANKS
  // ============================================================================
  {
    name: "Yemen Gulf Bank",
    nameAr: "بنك اليمن والخليج",
    acronym: "YGB",
    swiftCode: "YGBKYESA",
    bankType: "commercial",
    jurisdiction: "both",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 620,
    capitalAdequacyRatio: 17.5,
    nonPerformingLoans: 22.0,
    liquidityRatio: 38.0,
    returnOnAssets: 0.7,
    returnOnEquity: 4.8,
    branchCount: 18,
    employeeCount: 380,
    headquarters: "Al-Shawkani Street, Sana'a",
    foundedYear: 2001,
    website: "https://www.yg-bank.com",
    email: "info@yg-bank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Regional commercial bank. Focus on trade finance.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-013",
    licenseDate: "2001-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Emirates NBD",
    swiftStatus: "active",
    auditFirm: "Deloitte",
    lastAuditDate: "2024-03-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Hadhramout Commercial Bank",
    nameAr: "بنك حضرموت التجاري",
    acronym: "HCB",
    swiftCode: null,
    bankType: "commercial",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 280,
    capitalAdequacyRatio: 16.0,
    nonPerformingLoans: 18.0,
    liquidityRatio: 42.0,
    returnOnAssets: 0.8,
    returnOnEquity: 5.5,
    branchCount: 12,
    employeeCount: 220,
    headquarters: "Aldis, Al-Mukalla",
    foundedYear: 2005,
    website: "https://www.hadhramoutbank.com",
    email: "info@hadhramoutbank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Regional bank serving Hadhramout. Strong local presence.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-019",
    licenseDate: "2005-01-01",
    cbyRegulator: "aden",
    correspondentBanks: "National Bank of Yemen",
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  // ============================================================================
  // MICROFINANCE BANKS
  // ============================================================================
  {
    name: "Al-Kuraimi Islamic Microfinance Bank",
    nameAr: "بنك الكريمي الإسلامي للتمويل الأصغر",
    acronym: "KIMB",
    swiftCode: "KURAYESA",
    bankType: "microfinance",
    jurisdiction: "both",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 1100,
    capitalAdequacyRatio: 24.0,
    nonPerformingLoans: 8.0,
    liquidityRatio: 55.0,
    returnOnAssets: 2.2,
    returnOnEquity: 15.0,
    branchCount: 180,
    employeeCount: 2800,
    headquarters: "Haddah Street, Sana'a",
    foundedYear: 2010,
    website: "http://alkuraimi.com",
    email: "alkuraimi@alkuraimi.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Largest microfinance bank. Extensive branch network. Mobile money leader.",
    confidenceRating: "A",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-017",
    licenseDate: "2010-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Tadhamon Bank",
    swiftStatus: "active",
    auditFirm: "Ernst & Young",
    lastAuditDate: "2024-09-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Al-Kuraimi Islamic Bank",
    nameAr: "بنك الكريمي الإسلامي",
    acronym: "KIB",
    swiftCode: "KIBKYESA",
    bankType: "islamic",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 450,
    capitalAdequacyRatio: 22.0,
    nonPerformingLoans: 10.0,
    liquidityRatio: 50.0,
    returnOnAssets: 1.5,
    returnOnEquity: 10.0,
    branchCount: 25,
    employeeCount: 420,
    headquarters: "Arwa Street, Crater, Aden",
    foundedYear: 2018,
    website: "http://kibanks.com",
    email: "kib@kibanks.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Full Islamic bank arm of Kuraimi Group. Aden-focused operations.",
    confidenceRating: "A",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-018",
    licenseDate: "2018-01-01",
    cbyRegulator: "aden",
    correspondentBanks: "Al-Kuraimi Microfinance",
    swiftStatus: "active",
    auditFirm: "Ernst & Young",
    lastAuditDate: "2024-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Al-Amal Microfinance Bank",
    nameAr: "بنك الأمل للتمويل الأصغر",
    acronym: "AMB",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "both",
    ownership: "mixed",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 380,
    capitalAdequacyRatio: 20.0,
    nonPerformingLoans: 12.0,
    liquidityRatio: 45.0,
    returnOnAssets: 1.8,
    returnOnEquity: 11.0,
    branchCount: 85,
    employeeCount: 1200,
    headquarters: "Baghdad Street, Sana'a",
    foundedYear: 2009,
    website: "https://www.alamalbank.com",
    email: "info@alamalbank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Second largest MFI. Strong women's lending program. UNDP supported.",
    confidenceRating: "A",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-016",
    licenseDate: "2009-01-01",
    cbyRegulator: "both",
    correspondentBanks: "Yemen Bank for Reconstruction",
    swiftStatus: "unknown",
    auditFirm: "KPMG",
    lastAuditDate: "2024-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Al-Qutaibi Islamic Bank for Microfinance",
    nameAr: "بنك القطيبي الإسلامي للتمويل الأصغر",
    acronym: "QIBM",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 95,
    capitalAdequacyRatio: 18.0,
    nonPerformingLoans: 15.0,
    liquidityRatio: 40.0,
    returnOnAssets: 1.2,
    returnOnEquity: 7.5,
    branchCount: 12,
    employeeCount: 180,
    headquarters: "Al-Kathiri Tour, 90th St., Aden",
    foundedYear: 2015,
    website: "https://www.qtbbank.com",
    email: "info@qtbbank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Aden-based microfinance. Focus on small traders.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-020",
    licenseDate: "2015-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Bin Dowal Islamic Microfinance Bank",
    nameAr: "بنك بن دول للتمويل الأصغر",
    acronym: "BDIMB",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 65,
    capitalAdequacyRatio: 16.0,
    nonPerformingLoans: 18.0,
    liquidityRatio: 38.0,
    returnOnAssets: 0.9,
    returnOnEquity: 5.8,
    branchCount: 8,
    employeeCount: 120,
    headquarters: "Masha Tour, Al-Mukalla",
    foundedYear: 2016,
    website: "http://www.bank-bindowal.com",
    email: "info@bank-bindowal.al",
    isUnderWatch: false,
    watchReason: null,
    notes: "Hadhramout-focused microfinance. Family-owned.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-021",
    licenseDate: "2016-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Al-Bossten Bank for Microfinance",
    nameAr: "بنك البستان للتمويل الأصغر",
    acronym: "ABM",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 42,
    capitalAdequacyRatio: 15.0,
    nonPerformingLoans: 20.0,
    liquidityRatio: 35.0,
    returnOnAssets: 0.6,
    returnOnEquity: 4.0,
    branchCount: 5,
    employeeCount: 75,
    headquarters: "Buqrih, Al-Mukalla",
    foundedYear: 2017,
    website: null,
    email: null,
    isUnderWatch: false,
    watchReason: null,
    notes: "Small Hadhramout microfinance. Limited operations.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-022",
    licenseDate: "2017-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2022-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Aden Bank for Microfinance",
    nameAr: "بنك عدن للتمويل الأصغر",
    acronym: "ABMF",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 55,
    capitalAdequacyRatio: 17.0,
    nonPerformingLoans: 16.0,
    liquidityRatio: 42.0,
    returnOnAssets: 1.0,
    returnOnEquity: 6.5,
    branchCount: 8,
    employeeCount: 110,
    headquarters: "Saha Street, Aden",
    foundedYear: 2016,
    website: "https://www.adenbank.com",
    email: "faisali@adenbank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Aden city-focused microfinance.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-023",
    licenseDate: "2016-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Aliuma Bank for Islamic Microfinance",
    nameAr: "بنك اليمة للتمويل الأصغر الإسلامي",
    acronym: "ABIM",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 38,
    capitalAdequacyRatio: 16.0,
    nonPerformingLoans: 19.0,
    liquidityRatio: 36.0,
    returnOnAssets: 0.7,
    returnOnEquity: 4.5,
    branchCount: 6,
    employeeCount: 85,
    headquarters: "90th Street, Aden",
    foundedYear: 2018,
    website: "https://www.aliumabank.com",
    email: "info@aliumabank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Small Islamic microfinance in Aden.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-024",
    licenseDate: "2018-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Sharq Yemeni Bank for Islamic Microfinance",
    nameAr: "بنك شرق اليمن للتمويل الأصغر الإسلامي",
    acronym: "SYBIM",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 48,
    capitalAdequacyRatio: 15.5,
    nonPerformingLoans: 17.0,
    liquidityRatio: 40.0,
    returnOnAssets: 0.8,
    returnOnEquity: 5.2,
    branchCount: 7,
    employeeCount: 95,
    headquarters: "Saha Street, Marib",
    foundedYear: 2019,
    website: "https://www.syibank.com",
    email: "info@syibank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Marib-based microfinance. Growing presence.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-025",
    licenseDate: "2019-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Shumul Bank for Islamic Microfinance",
    nameAr: "بنك شمول للتمويل الأصغر الإسلامي",
    acronym: "SBIM",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 35,
    capitalAdequacyRatio: 14.5,
    nonPerformingLoans: 21.0,
    liquidityRatio: 34.0,
    returnOnAssets: 0.5,
    returnOnEquity: 3.5,
    branchCount: 5,
    employeeCount: 70,
    headquarters: "Saha Street, Aden",
    foundedYear: 2019,
    website: "https://www.shumilbank.com",
    email: "info@shumilbank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Small Aden microfinance.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-026",
    licenseDate: "2019-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "First Aden Islamic Bank",
    nameAr: "بنك عدن الإسلامي الأول",
    acronym: "FAIB",
    swiftCode: null,
    bankType: "islamic",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 72,
    capitalAdequacyRatio: 18.0,
    nonPerformingLoans: 14.0,
    liquidityRatio: 45.0,
    returnOnAssets: 1.1,
    returnOnEquity: 7.0,
    branchCount: 6,
    employeeCount: 95,
    headquarters: "90th Street, Aden",
    foundedYear: 2020,
    website: "https://www.firstaden-bank.com",
    email: "info@firstaden-bank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "New Islamic bank in Aden. Growing operations.",
    confidenceRating: "B",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-027",
    licenseDate: "2020-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2024-03-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Qasem Islamic Microfinance Bank",
    nameAr: "بنك قاسم الإسلامي للتمويل الأصغر",
    acronym: "QIMB",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 28,
    capitalAdequacyRatio: 14.0,
    nonPerformingLoans: 22.0,
    liquidityRatio: 32.0,
    returnOnAssets: 0.4,
    returnOnEquity: 2.8,
    branchCount: 4,
    employeeCount: 55,
    headquarters: "90th Street, Aden",
    foundedYear: 2020,
    website: "https://qasemislamicbank.com",
    email: null,
    isUnderWatch: false,
    watchReason: null,
    notes: "Small new microfinance bank.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-028",
    licenseDate: "2020-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Tamkeen Microfinance Bank",
    nameAr: "بنك تمكين للتمويل الأصغر",
    acronym: "TMB",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 32,
    capitalAdequacyRatio: 15.0,
    nonPerformingLoans: 19.0,
    liquidityRatio: 38.0,
    returnOnAssets: 0.6,
    returnOnEquity: 4.0,
    branchCount: 5,
    employeeCount: 65,
    headquarters: "Alsijn Street - Almansoura, Aden",
    foundedYear: 2021,
    website: "https://www.tamkeenbank-ye.com",
    email: "info@tamkeenbank-ye.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "New microfinance focusing on women entrepreneurs.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-029",
    licenseDate: "2021-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Amjad Islamic Microfinance Bank",
    nameAr: "بنك أمجاد الإسلامي للتمويل الأصغر",
    acronym: "AIMB",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 25,
    capitalAdequacyRatio: 14.0,
    nonPerformingLoans: 20.0,
    liquidityRatio: 35.0,
    returnOnAssets: 0.5,
    returnOnEquity: 3.2,
    branchCount: 4,
    employeeCount: 50,
    headquarters: "New Mansoura - Al Shihr - Hadhramaut",
    foundedYear: 2021,
    website: "https://www.AmjadIBank.com",
    email: "info@amjadbank.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Hadhramout coastal microfinance.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-030",
    licenseDate: "2021-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-06-30",
    boardChairman: null,
    ceo: null
  },
  {
    name: "Alsalam Capital Islamic Microfinance Bank",
    nameAr: "بنك السلام كابيتال الإسلامي للتمويل الأصغر",
    acronym: "ACIMB",
    swiftCode: null,
    bankType: "microfinance",
    jurisdiction: "aden",
    ownership: "private",
    operationalStatus: "operational",
    sanctionsStatus: "none",
    totalAssets: 22,
    capitalAdequacyRatio: 13.5,
    nonPerformingLoans: 18.0,
    liquidityRatio: 36.0,
    returnOnAssets: 0.4,
    returnOnEquity: 2.8,
    branchCount: 3,
    employeeCount: 42,
    headquarters: "Aden Street - Marib",
    foundedYear: 2022,
    website: "https://www.alsalamcapbank.com",
    email: "info@alsalamcb.com",
    isUnderWatch: false,
    watchReason: null,
    notes: "Newest licensed bank. Marib-based.",
    confidenceRating: "C",
    metricsAsOf: "2024-12-31",
    licenseNumber: "CBY-031",
    licenseDate: "2022-01-01",
    cbyRegulator: "aden",
    correspondentBanks: null,
    swiftStatus: "unknown",
    auditFirm: null,
    lastAuditDate: "2023-12-31",
    boardChairman: null,
    ceo: null
  }
];

async function seedAllBanks() {
  console.log('🏦 Starting comprehensive bank database seed...');
  console.log(`📊 Total banks to seed: ${allBanks.length}`);
  
  const conn = await mysql.createConnection(process.env.DATABASE_URL!);
  
  try {
    // Clear existing banks
    console.log('🗑️ Clearing existing bank records...');
    await conn.execute('DELETE FROM commercial_banks');
    
    // Insert all banks
    for (const bank of allBanks) {
      console.log(`  ➕ Adding: ${bank.acronym} - ${bank.name}`);
      
      await conn.execute(`
        INSERT INTO commercial_banks (
          name, nameAr, acronym, swiftCode, bankType, jurisdiction, ownership,
          operationalStatus, sanctionsStatus, totalAssets, capitalAdequacyRatio,
          nonPerformingLoans, liquidityRatio, returnOnAssets, returnOnEquity,
          branchCount, employeeCount, headquarters, foundedYear, website, email,
          isUnderWatch, watchReason, notes, confidenceRating, metricsAsOf
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        bank.name,
        bank.nameAr,
        bank.acronym,
        bank.swiftCode,
        bank.bankType,
        bank.jurisdiction,
        bank.ownership,
        bank.operationalStatus,
        bank.sanctionsStatus,
        bank.totalAssets,
        bank.capitalAdequacyRatio,
        bank.nonPerformingLoans,
        bank.liquidityRatio,
        bank.returnOnAssets,
        bank.returnOnEquity,
        bank.branchCount,
        bank.employeeCount,
        bank.headquarters,
        bank.foundedYear,
        bank.website,
        bank.email,
        bank.isUnderWatch ? 1 : 0,
        bank.watchReason,
        bank.notes,
        bank.confidenceRating,
        bank.metricsAsOf
      ]);
    }
    
    // Get summary stats
    const [stats] = await conn.execute(`
      SELECT 
        COUNT(*) as totalBanks,
        SUM(totalAssets) as totalAssets,
        SUM(CASE WHEN sanctionsStatus != 'none' THEN 1 ELSE 0 END) as sanctionedBanks,
        SUM(CASE WHEN jurisdiction = 'aden' THEN 1 ELSE 0 END) as adenBanks,
        SUM(CASE WHEN jurisdiction = 'sanaa' THEN 1 ELSE 0 END) as sanaaBanks,
        SUM(CASE WHEN jurisdiction = 'both' THEN 1 ELSE 0 END) as bothBanks,
        SUM(branchCount) as totalBranches,
        SUM(employeeCount) as totalEmployees
      FROM commercial_banks
    `);
    
    console.log('\n✅ Bank seeding complete!');
    console.log('📊 Summary:');
    console.log(stats);
    
  } finally {
    await conn.end();
  }
}

// Run if called directly
seedAllBanks().catch(console.error);

export { allBanks, seedAllBanks };
